# https://aka.ms/yaml

trigger:
- master
jobs:
  - job: 'ubuntu'
    displayName: 'Ubuntu'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        docker build -t synther .
      displayName: 'Build image'
    - script: |
        docker run --name synther_cont synther
        mkdir build
        docker cp synther_cont:/build build
      displayName: 'Copy build'
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: build
        artifactName: drop
    