# https://aka.ms/yaml

trigger:
- master
pr:
- master
jobs:
  - job: 'ubuntu'
    displayName: 'Ubuntu'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        docker build -t synther .
      displayName: 'Create image'
    - script: |
        docker run -it synther
      displayName: 'Build package'