# https://aka.ms/yaml

trigger:
- master
pr:
- master
jobs:
  - job: 'windows'
    displayName: 'Windows'
    pool:
      vmImage: 'windows-latest'
    steps:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH
    - script: |
        conda env create -f environment.yml
        source activate synther
        conda build . --output-folder build
      displayName: 'Build'
#  - job: 'ubuntu'
#    displayName: 'Ubuntu'
#    pool:
#      vmImage: 'ubuntu-latest'
#    steps:
#    - script: |
#        conda env create -f environment.yml
#        conda-build . --output-folder build
#      displayName: 'Build'